plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
	id 'net.neoforged.moddev' version '2.0.141'
}

version = '1.24'
group = 'bl4ckscor3.mod.scserverutils'

base {
	archivesName = 'scserverutils-26.1.2'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

neoForge {
	version = "26.1.2.78"

	runs {
		configureEach {
			logLevel = org.slf4j.event.Level.DEBUG
			gameDirectory = project.file("runs/" + name)
			ideName = "SCServerUtils " + ideName.get()
		}

		client {
			client()
		}

		server {
			server()
			programArgument('-nogui')
		}
	}

	mods {
		scserverutils {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				url "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	flatDir {
		dirs("libs")
	}
}

dependencies {
    implementation "curse.maven:security-craft-64760:8336505"

    implementation "local:craterlib-867099:8117951"
    implementation "curse.maven:simple-discord-link-bot-forge-fabric-spigot-541320:8437065"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "SC Server Utils",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "SC Server Utils",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 25
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}