license="ARR"
issueTrackerURL="https://discord.gg/U8DvBAW"
displayURL="https://discord.gg/U8DvBAW"
authors="bl4ckscor3"

[[mods]]
	modId="scserverutils"
	version="${file.jarVersion}"
	displayName="SC Server Utils"
	description='''Adds player and moderator utilities for the official SecurityCraft server.'''

[[mixins]]
	config="scserverutils.mixins.json"

[[mixins]]
	config="scserverutils.hidden.mixins.json"

[[dependencies.scserverutils]]
	modId="neoforge"
	type="required"
	versionRange="[21.10,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.scserverutils]]
	modId="minecraft"
	type="required"
	versionRange="[1.21.10,)"
	ordering="NONE"
	side="BOTH"